from __future__ import annotations

from pathlib import Path
import re
from typing import Iterable

from .models import DesignPlan


def _sanitize_name(value: str) -> str:
    sanitized = re.sub(r"\W", "_", value)
    if not sanitized:
        sanitized = "NET"
    if sanitized[0].isdigit():
        sanitized = f"N_{sanitized}"
    return sanitized


def _component_line(ref: str, value: str, footprint: str, symbol: str) -> str:
    return (
        f"    '{ref}': {{'value': '{value}', 'footprint': '{footprint}', "
        f"'symbol': '{symbol}'}},"
    )


def _iter_unique_pins(nodes: Iterable[str]) -> list[str]:
    seen = set()
    result: list[str] = []
    for node in nodes:
        if node not in seen:
            result.append(node)
            seen.add(node)
    return result


def build_skidl_script(plan: DesignPlan) -> str:
    lines: list[str] = []
    lines.append("# Auto-generated by AI PCB Agent")
    lines.append("# Requires: pip install skidl")
    lines.append("from skidl import *")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("set_default_tool(KICAD)")
    lines.append("_sys_symbol_dir = Path('/usr/share/kicad/symbols')")
    lines.append("if _sys_symbol_dir.exists():")
    lines.append("    lib_search_paths[KICAD].append(str(_sys_symbol_dir))")
    lines.append("")
    lines.append("parts = {")

    for comp in plan.components:
        lines.append(
            _component_line(
                ref=comp.ref,
                value=comp.value,
                footprint=comp.footprint,
                symbol=comp.symbol,
            )
        )
    lines.append("}")
    lines.append("")
    lines.append("def _generic_symbol_for_ref(ref: str) -> str:")
    lines.append("    prefix = (ref[:1] or '').upper()")
    lines.append("    return {")
    lines.append("        'R': 'Device:R',")
    lines.append("        'C': 'Device:C',")
    lines.append("        'D': 'Device:LED',")
    lines.append("        'Q': 'Transistor_BJT:2N3904',")
    lines.append("        'J': 'Connector_Generic:Conn_01x03',")
    lines.append("        'U': 'Amplifier_Operational:LM358',")
    lines.append("    }.get(prefix, 'Device:R')")
    lines.append("")
    lines.append("def _try_make_part(symbol: str, ref: str, value: str, footprint: str):")
    lines.append("    candidates = []")
    lines.append("    if symbol and ':' in symbol:")
    lines.append("        lib, part = symbol.split(':', 1)")
    lines.append("        candidates.append((lib, part))")
    lines.append("        if value:")
    lines.append("            candidates.append((lib, value))")
    lines.append("    generic_symbol = _generic_symbol_for_ref(ref)")
    lines.append("    if ':' in generic_symbol:")
    lines.append("        glib, gpart = generic_symbol.split(':', 1)")
    lines.append("        candidates.append((glib, gpart))")
    lines.append("        if value:")
    lines.append("            candidates.append((glib, value))")
    lines.append("")
    lines.append("    tried = set()")
    lines.append("    for lib_name, part_name in candidates:")
    lines.append("        key = (lib_name, part_name)")
    lines.append("        if key in tried:")
    lines.append("            continue")
    lines.append("        tried.add(key)")
    lines.append("        try:")
    lines.append("            return Part(lib_name, part_name, ref=ref, value=value, footprint=footprint)")
    lines.append("        except Exception:")
    lines.append("            pass")
    lines.append("    raise RuntimeError(f'Part resolve failed: ref={ref}, symbol={symbol}, value={value}')")
    lines.append("")
    lines.append("instances = {}")
    lines.append("for ref, cfg in parts.items():")
    lines.append("    instances[ref] = _try_make_part(")
    lines.append("        symbol=cfg['symbol'],")
    lines.append("        ref=ref,")
    lines.append("        value=cfg['value'],")
    lines.append("        footprint=cfg['footprint'],")
    lines.append("    )")
    lines.append("")

    for net in plan.nets:
        net_var = _sanitize_name(net.net_name)
        lines.append(f"net_{net_var} = Net('{net.net_name}')")
        for node in _iter_unique_pins(net.nodes):
            if "." not in node:
                continue
            ref, pin = node.split(".", 1)
            lines.append(f"net_{net_var} += instances['{ref}']['{pin}']")
        lines.append("")

    lines.append("ERC()")
    lines.append("generate_netlist()")
    lines.append("")
    return "\n".join(lines)


def build_design_report(plan: DesignPlan) -> str:
    lines: list[str] = []
    lines.append(f"# {plan.title}")
    lines.append("")
    lines.append("## Assumptions")
    for item in plan.assumptions:
        lines.append(f"- {item}")

    lines.append("")
    lines.append("## Components")
    for comp in plan.components:
        lines.append(
            f"- {comp.ref}: {comp.value} | {comp.symbol} | {comp.footprint}"
        )
        if comp.notes:
            lines.append(f"  - note: {comp.notes}")

    lines.append("")
    lines.append("## Nets")
    for net in plan.nets:
        lines.append(f"- {net.net_name}: {', '.join(net.nodes)}")

    lines.append("")
    lines.append("## Placement Hints")
    for hint in plan.placement_hints:
        lines.append(f"- {hint.target}: {hint.hint}")

    lines.append("")
    lines.append("## Checks")
    for check in plan.design_checks:
        lines.append(f"- {check}")

    return "\n".join(lines)


def write_kicad_compatible_outputs(plan: DesignPlan, out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)

    report_file = out_dir / "design_plan.md"
    json_file = out_dir / "design_plan.json"
    skidl_file = out_dir / "generated_circuit.py"

    report_file.write_text(build_design_report(plan), encoding="utf-8")
    json_file.write_text(plan.model_dump_json(indent=2), encoding="utf-8")
    skidl_file.write_text(build_skidl_script(plan), encoding="utf-8")

    return {
        "report": report_file,
        "json": json_file,
        "skidl": skidl_file,
    }
